const crypto = require('crypto');

// Your new secret key
const SECRET_KEY = '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';

// Example: Replace these with your actual query parameters from Shopify callback URL
// Note: Timestamp is automatically generated by Shopify when redirecting
// For testing, we use current timestamp (Shopify will send its own timestamp)
const params = {
    shop: 'rohit-12345839.myshopify.com',  // Replace with your shop
    code: '62affa8c15a163f022172b71cc2b87f2',  // Replace with code from Shopify
    timestamp: Math.floor(Date.now() / 1000).toString(),  // Current Unix timestamp (Shopify will send its own)
    // state: 'optional_state'         // Add if present
};

// Remove hmac and signature, sort alphabetically, create message
const { hmac: _, signature: __, ...cleanParams } = params;
const message = Object.keys(cleanParams)
    .sort()
    .map(key => `${key}=${cleanParams[key]}`)
    .join('&');

// Calculate HMAC
const calculatedHmac = crypto
    .createHmac('sha256', SECRET_KEY)
    .update(message)
    .digest('hex');

console.log('Message:', message);
console.log('New HMAC:', calculatedHmac);

